insert into public.books (
  title,
  author,
  description,
  category,
  published_year,
  publisher,
  language,
  isbn,
  cover_url,
  open_library_work_key,
  open_library_edition_key,
  source,
  has_file,
  download_url,
  file_format,
  file_size_bytes,
  is_public
)
values
  (
    'Introduction to Artificial Intelligence',
    'Sarah Johnson',
    'A practical introduction to AI concepts, history, and modern applications.',
    'Computer Science',
    2024,
    'AI Press',
    'English',
    '9780000000001',
    null,
    null,
    null,
    'manual',
    false,
    null,
    null,
    null,
    true
  ),
  (
    'Machine Learning Fundamentals',
    'Emily Rodriguez',
    'An accessible foundation in supervised learning, evaluation, and model building.',
    'Data Science',
    2023,
    'Insight Academic',
    'English',
    '9780000000002',
    null,
    null,
    null,
    'manual',
    true,
    'https://example.com/books/machine-learning-fundamentals.pdf',
    'PDF',
    16482304,
    true
  ),
  (
    'The Open Library Book',
    'Open Library Demo Author',
    'Example imported metadata record for testing an Open Library based workflow.',
    'Reference',
    2022,
    'Open Demo House',
    'English',
    '9780000000003',
    'https://covers.openlibrary.org/b/id/10521270-L.jpg',
    '/works/OL45883W',
    '/books/OL7353617M',
    'open_library',
    false,
    null,
    null,
    null,
    true
  );
